# Generated by Django 4.1.7 on 2023-03-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_song_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='band_id',
            new_name='band',
        ),
        migrations.RenameField(
            model_name='albumreview',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='albumreviewcomment',
            old_name='album_review_id',
            new_name='album_review',
        ),
        migrations.RenameField(
            model_name='albumreviewlike',
            old_name='album_review_id',
            new_name='album_review',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album_id',
            new_name='album',
        ),
    ]
